repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace  # trailing whitespace
    -   id: end-of-file-fixer    # files end with a newline

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort                # Sorts imports
        args: ["--profile", "black"]
